### ISSUE TITLE
Typo in repository name

### ISSUE THREAD

**Issue by flash-me** [Apress/java-17-for-absolute-beginners#1]
![image](https://user-images.githubusercontent.com/5240450/153294306-e0685a30-eab1-498c-a7da-f6cd103e32ff.png)

Oops 🤷🏽‍♂️

cheers
flash ⚡

**Comment by iuliana** [comment]
Well  ... fuck!

**Comment by flash-me** [comment]
I realized this issue while following the instructions on page 49 in the book. The git clone fails apparently

![image](https://user-images.githubusercontent.com/5240450/153777201-8252f61f-78a3-4e57-a3e6-c4f36d298314.png)

So I had to search for the actual repository by myself. 

cheers
flash ⚡

**Comment by iuliana** [comment]
@flash-me, 

Unfortunately I don't have administrative rights over the Apress GitHub organization and I cannot rectify this myself. I've already reported this up the chain, but I"m not sure when it will be solved.  :( This is why, the issues is still open. 

Thank you for reporting it. 

Cheers!

**Comment by iuliana** [comment]
@flash-me Issue was resolved!
Thank you for the feedback!
